name: iOS Dev CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Java (chỉ để build runner, Flutter cần Java)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.8"

      # 4. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 5. Code generation
      - name: Run code generation
        run: dart run build_runner build --delete-conflicting-outputs

      # 6. Dart format
      - name: Check code formatting
        run: dart format --set-exit-if-changed .

      # 7. Flutter analyze
      - name: Run analyzer
        run: flutter analyze

      # 8. Build IPA (dev flavor)
      - name: Build iOS (dev flavor)
        run: flutter build ipa --release --flavor dev -t lib/main_dev.dart
